#!/bin/bash
ln -s $(pwd)/.bashrc ~/.bashrc
ln -s $(pwd)/.emacs ~/.emacs

chmod +x $(pwd)/.xsession
ln -s $(pwd)/.xsession ~/.xsession

rm -rf ~/.config/awesome
ln -s $(pwd)/awesome ~/.config

ln -s $(pwd)/.tmux.conf ~/.tmux.conf
