#!/bin/bash
ln -s $(pwd)/.bashrc ~/.bashrc
ln -s $(pwd)/.emacs ~/.emacs

chmod +x $(pwd)/.xsession
ln -s $(pwd)/.xsession ~/.xsession

rm -rf ~/.config/awesome
ln -s $(pwd)/awesome ~/.config

ln -s $(pwd)/.tmux.conf ~/.tmux.conf

mkdir -p ~/.config/mpv
ln -s $(pwd)/mpv/mpv.conf ~/.config/mpv/mpv.conf

mkdir -p ~/.config/ytfzf/conf.sh